[tool.poetry]
name = "myazo"
version = "0.6.0"
description = "Self-hosted, cross-platform Gyazo alternative"
authors = ["Miguel de Moura"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"
requests = "^2.22.0"
pyperclip = "^1.7.0"
pillow = "^6.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
